# Generated by Django 5.2 on 2025-06-20 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customerprofile_delete_customerprofle'),
        ('manager', '0014_alter_ricepost_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_For_Rice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rice_customer_payments', to='manager.ricepost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_rice_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Rice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_purchased', models.FloatField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('payment', models.BooleanField(default=False)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_rice_purchases', to=settings.AUTH_USER_MODEL)),
                ('rice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_rice_orders', to='manager.ricepost')),
            ],
        ),
    ]
