# Generated by Django 5.2 on 2025-06-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_payment_for_rice_purchase_rice'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_rice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Successful', 'Successful')], default='Pending', max_length=20),
        ),
    ]
