# Generated by Django 5.2 on 2025-06-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_purchase_rice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_rice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered'), ('Successful', 'Successful')], default='Pending', max_length=20),
        ),
    ]
