# Generated by Django 5.2 on 2025-07-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_purchase_rice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_rice',
            name='profit_or_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
