# Generated by Django 5.2 on 2025-09-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_customerprofile_transaction_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCostSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_cost', models.DecimalField(decimal_places=2, default=50.0, help_text='Base delivery cost in Taka', max_digits=6)),
                ('cost_per_kg', models.DecimalField(decimal_places=2, default=5.0, help_text='Additional cost per kg in Taka', max_digits=6)),
                ('max_delivery_cost', models.DecimalField(decimal_places=2, default=200.0, help_text='Maximum delivery cost cap in Taka', max_digits=6)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable these settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Cost Setting',
                'verbose_name_plural': 'Delivery Cost Settings',
            },
        ),
    ]
