# Generated by Django 5.2 on 2025-09-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_deliverycostsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='email',
            field=models.EmailField(default='user@example.com', max_length=255),
            preserve_default=False,
        ),
    ]
