# Generated by Django 5.2 on 2025-04-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
