# Generated by Django 5.2 on 2025-04-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_paddystock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paddystock',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
