# Generated by Django 5.2 on 2025-04-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0003_alter_paddystock_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paddystock',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
