# Generated by Django 5.2 on 2025-04-25 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0004_alter_paddystock_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paddystock',
            options={'ordering': ['-stored_since']},
        ),
        migrations.AddField(
            model_name='paddystock',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo of the paddy.', null=True, upload_to='paddy_images/'),
        ),
        migrations.AddField(
            model_name='paddystock',
            name='name',
            field=models.CharField(default='BIRRI 28', help_text='Name or type of the paddy (e.g., BRRI Dhan 28)', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paddystock',
            name='moisture_content',
            field=models.DecimalField(decimal_places=1, help_text='Moisture content (%)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='paddystock',
            name='price_per_mon',
            field=models.DecimalField(decimal_places=2, help_text='Price per mon (or other unit)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paddystock',
            name='quality_notes',
            field=models.TextField(blank=True, help_text='Any notes about the quality.'),
        ),
        migrations.AlterField(
            model_name='paddystock',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Quantity in kg, ton, or mon.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
