# Generated by Django 5.2 on 2025-04-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0005_alter_paddystock_options_paddystock_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='union',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='upazila',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
