# Generated by Django 5.2 on 2025-07-11 16:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0006_dealerprofile_address_dealerprofile_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaddyPurchaseFromFarmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('farmer_phone', models.CharField(blank=True, max_length=15)),
                ('paddy_type', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('purchase_price_per_mon', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moisture_content', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(25)])),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('reference_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.dealerprofile')),
                ('paddy_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='dealer.paddystock')),
            ],
        ),
    ]
