# Generated by Django 5.2 on 2025-07-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0007_paddypurchasefromfarmer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paddystock',
            options={'ordering': ['-last_updated']},
        ),
        migrations.AddField(
            model_name='paddystock',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paddystock',
            name='average_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paddystock',
            name='average_transport_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paddystock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paddystock',
            name='moisture_category',
            field=models.CharField(choices=[('Easy', 'Easy (≤13.5%)'), ('Medium', 'Medium (13.6%–15.5%)'), ('Hard', 'Hard (>15.5%)')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='paddystock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='paddy_images/'),
        ),
        migrations.AlterField(
            model_name='paddystock',
            name='moisture_content',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='paddystock',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paddystock',
            name='price_per_mon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paddystock',
            name='quality_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paddystock',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='paddystock',
            unique_together={('dealer', 'name', 'moisture_category')},
        ),
    ]
