# Generated by Django 5.2 on 2025-07-12 06:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0008_alter_paddystock_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketplace_images/')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('moisture_content', models.DecimalField(decimal_places=1, max_digits=4)),
                ('price_per_mon', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality_notes', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Sold', 'Sold')], default='Draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.dealerprofile')),
                ('paddy_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_posts', to='dealer.paddystock')),
            ],
        ),
    ]
