# Generated by Django 5.2 on 2025-07-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0009_marketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='paddystock',
            name='other_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
