# Generated by Django 5.2 on 2025-07-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0010_paddystock_other_costs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paddystock',
            old_name='other_costs',
            new_name='average_other_cost',
        ),
    ]
