# Generated by Django 5.2 on 2025-07-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0011_rename_other_costs_paddystock_average_other_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketplace',
            old_name='created_at',
            new_name='stored_since',
        ),
    ]
