# Generated by Django 5.2 on 2025-04-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ricepost',
            name='rice_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
