# Generated by Django 5.2 on 2025-04-26 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_purchase_paddy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('paymant_method', models.CharField(default='MockPay', max_length=40)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager.purchase_paddy')),
            ],
        ),
    ]
