# Generated by Django 5.2 on 2025-04-30 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_purchaserice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
