# Generated by Django 5.2 on 2025-04-30 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0006_dealerprofile_address_dealerprofile_district_and_more'),
        ('manager', '0009_delete_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_paddy',
            name='paddy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_paddy', to='dealer.paddystock'),
        ),
        migrations.CreateModel(
            name='PaymentForPaddy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paddy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.paddystock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
