# Generated by Django 5.2 on 2025-04-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_alter_purchase_paddy_paddy_paymentforpaddy'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_paddy',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaserice',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
