# Generated by Django 5.2 on 2025-04-30 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_paymentforrice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserice',
            name='rice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseRice', to='manager.ricepost'),
        ),
    ]
