# Generated by Django 5.2 on 2025-06-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_alter_ricepost_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_paddy',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered'), ('Successful', 'Successful')], default='Pending', max_length=20),
        ),
    ]
