# Generated by Django 5.2 on 2025-06-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_purchase_paddy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='transaction_password',
            field=models.CharField(blank=True),
        ),
    ]
