# Generated by Django 5.2 on 2025-06-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_managerprofile_transaction_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered'), ('Successful', 'Successful'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
