# Generated by Django 5.2 on 2025-07-04 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_purchaserice_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_paddy',
            name='moisture_content',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Moisture content (%)', max_digits=4, null=True),
        ),
        migrations.CreateModel(
            name='PaddyStockOfManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paddy_name', models.CharField(max_length=100)),
                ('moisture_content', models.DecimalField(blank=True, decimal_places=1, help_text='Moisture content (%)', max_digits=4, null=True)),
                ('rice_type', models.CharField(blank=True, max_length=100, null=True)),
                ('total_quantity', models.FloatField(help_text='In kg')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_price_per_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='paddy_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Manager's Paddy Stock",
                'verbose_name_plural': "Manager's Paddy Stocks",
            },
        ),
    ]
