# Generated by Django 5.2 on 2025-07-06 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_purchase_paddy_moisture_content_paddystockofmanager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiceStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rice_name', models.CharField(max_length=100)),
                ('quality', models.CharField(blank=True, max_length=100, null=True)),
                ('rice_type', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_quantity', models.FloatField(help_text='In kg')),
                ('average_price_per_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='rice_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rice Stock',
                'verbose_name_plural': 'Rice Stocks',
            },
        ),
    ]
