# Generated by Django 5.2 on 2025-07-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_ricestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='ricestock',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
