# Generated by Django 5.2 on 2025-07-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_ricestock_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricestock',
            name='average_price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='ricestock',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total value of current stock', max_digits=10),
        ),
    ]
