# Generated by Django 5.2 on 2025-07-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_alter_ricestock_average_price_per_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserice',
            name='profit_or_loss',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
