# Generated by Django 5.2 on 2025-09-23 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0012_rename_created_at_marketplace_stored_since'),
        ('manager', '0022_purchaserice_profit_or_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentforpaddy',
            name='paddy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.marketplace'),
        ),
        migrations.AlterField(
            model_name='purchase_paddy',
            name='paddy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_paddy', to='dealer.marketplace'),
        ),
    ]
